version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: fastapi-application
    environment:
      MONGO_URL: mongodb://mongodb:27017/weather
      PORT: 8000
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - app-network
    restart: "no"

  # mongo-express:
  #   image: mongo-express:0.54
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: false
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - app-network

volumes:
  dbdata6:

networks:
  app-network:
    driver: bridge
